import { SunOptions } from "./classes/Sun";
import { PlanetOptions } from "./types";

export const sunData: SunOptions = {
  name: "Sun",
  radius: 4,
  rotationPeriod: 25,
  lightIntensity: 20,
  textureURL: "/textures/2k_sun.jpg",
  info: {
    mass: "1.989 × 10^30 kg",
    radius: "696,340 km",
    temperature: "5,778 K",
    composition: "Hydrogen, Helium",
    age: "4.603 billion years",
  },
};

export const planetsData: PlanetOptions[] = [
  {
    name: "Mercury",
    radius: 0.4,
    distance: 8,
    orbitPeriod: 88,
    rotationPeriod: 1407,
    textureURL: "/textures/2k_mercury.jpg",
    info: {
      mass: "3.30 × 10^23 kg",
      radius: "2,440 km",
      gravity: "3.7 m/s²",
      distanceFromSun: "57.9 million km",
      numberOfMoons: 0,
      atmosphere: "Trace (exosphere: O, Na, H, He, K)",
      composition: "Rocky, iron core",
    },
  },
  {
    name: "Venus",
    radius: 0.95,
    distance: 11,
    orbitPeriod: 225,
    rotationPeriod: -5832,
    textureURL: "/textures/2k_venus_surface.jpg",
    info: {
      mass: "4.87 × 10^24 kg",
      radius: "6,052 km",
      gravity: "8.87 m/s²",
      distanceFromSun: "108.2 million km",
      numberOfMoons: 0,
      atmosphere: "CO₂, N₂",
      composition: "Rocky",
      temperature: "737 K (surface)",
    },
  },
  {
    name: "Earth",
    radius: 1,
    distance: 14,
    orbitPeriod: 365,
    rotationPeriod: 24,
    textureURL: "/textures/2k_earth_daymap.jpg",
    moons: [
      {
        name: "Moon",
        radius: 0.27,
        distance: 2,
        orbitPeriod: 27,
        rotationPeriod: 655,
        textureURL: "/textures/2k_moon.jpg",
      },
    ],
    info: {
      mass: "5.97 × 10^24 kg",
      radius: "6,371 km",
      gravity: "9.8 m/s²",
      distanceFromSun: "149.6 million km",
      numberOfMoons: 1,
      atmosphere: "Nitrogen, Oxygen",
      composition: "Rocky",
    },
  },
  {
    name: "Mars",
    radius: 0.53,
    distance: 18,
    orbitPeriod: 687,
    rotationPeriod: 24.6,
    textureURL: "/textures/2k_mars.jpg",
    info: {
      mass: "6.42 × 10^23 kg",
      radius: "3,390 km",
      gravity: "3.71 m/s²",
      distanceFromSun: "227.9 million km",
      numberOfMoons: 2,
      atmosphere: "CO₂, N₂, Ar",
      composition: "Rocky",
      temperature: "210 K (average)",
    },
  },
  {
    name: "Jupiter",
    radius: 2.2,
    distance: 25,
    orbitPeriod: 4333,
    rotationPeriod: 9.9,
    textureURL: "/textures/2k_jupiter.jpg",
    info: {
      mass: "1.90 × 10^27 kg",
      radius: "69,911 km",
      gravity: "24.79 m/s²",
      distanceFromSun: "778.5 million km",
      numberOfMoons: 95,
      atmosphere: "H₂, He",
      composition: "Gas giant",
      temperature: "165 K (cloud tops)",
    },
  },
  {
    name: "Saturn",
    radius: 1.9,
    distance: 32,
    orbitPeriod: 10759,
    rotationPeriod: 10.7,
    textureURL: "/textures/2k_saturn.jpg",
    ring: {
      innerRadius: 2.2,
      outerRadius: 3.5,
      textureURL: "/textures/2k_saturn_ring_alpha.png",
    },
    info: {
      mass: "5.68 × 10^26 kg",
      radius: "58,232 km",
      gravity: "10.44 m/s²",
      distanceFromSun: "1.43 billion km",
      numberOfMoons: 145,
      atmosphere: "H₂, He",
      composition: "Gas giant",
      rings: "Ice and rock particles",
      temperature: "134 K (cloud tops)",
    },
  },
  {
    name: "Uranus",
    radius: 1.6,
    distance: 40,
    orbitPeriod: 30687,
    rotationPeriod: -17.2,
    textureURL: "/textures/2k_uranus.jpg",
    ring: { innerRadius: 1.7, outerRadius: 2.3 },
    info: {
      mass: "8.68 × 10^25 kg",
      radius: "25,362 km",
      gravity: "8.69 m/s²",
      distanceFromSun: "2.87 billion km",
      numberOfMoons: 27,
      atmosphere: "H₂, He, CH₄",
      composition: "Ice giant",
      temperature: "76 K (cloud tops)",
    },
  },
  {
    name: "Neptune",
    radius: 1.5,
    distance: 47,
    orbitPeriod: 60190,
    rotationPeriod: 16,
    textureURL: "/textures/2k_neptune.jpg",
    info: {
      mass: "1.02 × 10^26 kg",
      radius: "24,622 km",
      gravity: "11.15 m/s²",
      distanceFromSun: "4.50 billion km",
      numberOfMoons: 14,
      atmosphere: "H₂, He, CH₄",
      composition: "Ice giant",
      temperature: "72 K (cloud tops)",
    },
  },
];
